### ISSUE TITLE
Add support for loading other question sets

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia-Widget-Dev-Kit#6] opened 2018-08-24 17:43 UTC
The player and creator are hardwired to load the demo.json qset.  It would be great to be able to paste/edit other qsets and select them instead of the demo.json set.

**Comment by FrenjaminBanklin** [comment] 2019-01-20 17:04
Duplicate of #36.

**Closed by FrenjaminBanklin** 2019-01-20 17:04 UTC
